name: First test

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - "**"
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  call_terraform_ci:
    uses: IvanGrishin3/githubactions/.github/workflows/workflow.yml@main
    with:
      REGION: eu-north-1
      ROLE_ARN: arn:aws:iam::093591452678:role/test_role
