name: Terraform CI


on:
  branches:
    - "**"
  pull_request:
  workflow_dispatch:


permissions:
  id-token: write
  contents: read

env:
  ENVIRONMENT_NAME: TEST
  ROLE_ARN: arn:aws:iam::093591452678:role/test_role
  REGION: eu-north-1
  TF_ROOT: .

jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.TF_ROOT }}
        
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
          
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.REGION }}
          role-to-assume: ${{ env.ROLE_ARN }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.0

      - name: Terraform Init
        run: terraform init -reconfigure

      - name: Terraform validate
        run: terraform validate

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan -out=tfplan.cache
        
      - name: Save Terraform Artifacts (Plan, Lock, Workspace)
        uses: actions/upload-artifact@v4
        with:
          name: terraform-artifacts
          path: |
            ${{ env.TF_ROOT }}/tfplan.cache
            ${{ env.TF_ROOT }}/.terraform.lock.hcl

  manual_approval:
    name: Manual Approval
    runs-on: ubuntu-latest
    needs: terraform_plan
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    permissions:
      issues: write
    steps:
      - name: Await Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: IvanGrishin3
          minimum-approvals: 1
          issue-title: "Terraform Apply Approval Required"
          issue-body: "Approve or deny the deployment to apply Terraform changes."
          exclude-workflow-initiator-as-approver: false

  terraform_apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: manual_approval
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    defaults:
      run:
        working-directory: ${{ env.TF_ROOT }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.REGION }}
          role-to-assume: ${{ env.ROLE_ARN }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.0

      - name: Download Terraform Artifacts
        uses: actions/download-artifact@v4
        with:
          name: terraform-artifacts
          path: ${{ env.TF_ROOT }}

      - name: Terraform Init
        run: terraform init -reconfigure

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan.cache
