name: Terraform CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - "**"
    types:
      - opened
      - synchronize
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  ENVIRONMENT_NAME: TEST
  ROLE_ARN: arn:aws:iam::093591452678:role/test_role
  REGION: eu-north-1

jobs:
  terraform_plan:
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
          
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.REGION }}
          role-to-assume: ${{ env.ROLE_ARN }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.0

      - name: Terraform Init
        run: terraform init -reconfigure

      - name: Terraform validate
        run: terraform validate

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan -out=tfplan.cache

      - name: Terraform Apply (only on main/master)
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        run: terraform apply -auto-approve tfplan.cache
