name: Terraform CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - "**"
    types:
      - opened
      - synchronize
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  ENVIRONMENT_NAME: TEST
  ROLE_ARN: arn:aws:iam::093591452678:role/test_role
  REGION: eu-north-1

jobs:
  terraform_plan:
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
          
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.REGION }}
          role-to-assume: ${{ env.ROLE_ARN }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.0

      - name: Terraform Init
        run: terraform init -reconfigure

      - name: Save .terraform directory
        uses: actions/upload-artifact@v4
        with:
          name: terraform-init
          path: .terraform/

      - name: Save terraform.lock.hcl
        uses: actions/upload-artifact@v4
        with:
          name: terraform-lock
          path: terraform.lock.hcl

      - name: Terraform validate
        run: terraform validate

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan

  terraform_apply:
    runs-on: ubuntu-latest
    needs: terraform_plan

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.REGION }}
          role-to-assume: ${{ env.ROLE_ARN }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.0

      - name: Download .terraform directory
        uses: actions/download-artifact@v4
        with:
          name: terraform-init
          path: .terraform/

      - name: Download terraform.lock.hcl
        uses: actions/download-artifact@v4
        with:
          name: terraform-lock
          path: .

      - name: Terraform Apply
        run: terraform apply -auto-approve
